"""Deterministic contracts for complete, resumable legislative research."""

from .collector import (
    CollectionCoverage,
    MetadataCollection,
    MetadataCollector,
    MetadataKind,
    MetadataPartition,
    PageProvenance,
    PartitionProvenance,
)
from .contracts import (
    DEFAULT_EVIDENCE_TYPES,
    CoverageLedger,
    EvidenceCoverage,
    EvidencePage,
    EvidenceType,
    ResearchContract,
    ResearchIntent,
    StableCursor,
)
from .credentials import ResearchCredential, ResearchCredentialCodec
from .document_worker import (
    DocumentWorkerError,
    DocumentWorkResult,
    FailureDisposition,
    OfficialDocumentWorker,
    PermanentDocumentError,
    TransientDocumentError,
)
from .documents import (
    FilesystemOfficialDocumentStore,
    OfficialDocumentKind,
    OfficialDocumentStore,
    ParsedOfficialDocument,
    RawOfficialDocument,
    TextSegment,
)
from .job_storage import SQLiteResearchJobStore
from .jobs import (
    InMemoryResearchJobStore,
    JobStatus,
    ResearchJob,
    ResearchJobStore,
)
from .partitioning import (
    DEFAULT_ASSEMBLY_TERM_BOUNDS,
    OFFICIAL_RESEARCH_SOURCES,
    DeferredSourceRequirement,
    MonthBucket,
    OfficialSource,
    OfficialSourceKind,
    PartitionCoverageExpectation,
    PartitionSearchTerm,
    PlannedMetadataPartition,
    ResearchPartitionPlan,
    ResearchPartitionPlanner,
    SearchTermRole,
    plan_partitions,
)
from .planner import (
    IntentEvidence,
    InterpretedScope,
    ResearchContractPlanner,
    ResearchPlan,
    plan_research,
)
from .queue import (
    LeasedResearchTask,
    ResearchTask,
    ResearchTaskQueue,
    ResearchTaskStage,
    VercelResearchTaskQueue,
)
from .resolver import (
    CandidateDecision,
    CandidateSetResolution,
    ExactBillNotFoundError,
    MetadataCandidateResolver,
    MetadataResolution,
    resolve_metadata_candidates,
)
from .results import (
    EvidenceCitation,
    EvidenceRecord,
    ResearchResultPage,
    ResearchSnapshot,
    snapshot_payload,
)

__all__ = [
    "DEFAULT_ASSEMBLY_TERM_BOUNDS",
    "DEFAULT_EVIDENCE_TYPES",
    "OFFICIAL_RESEARCH_SOURCES",
    "DeferredSourceRequirement",
    "DocumentWorkResult",
    "DocumentWorkerError",
    "FailureDisposition",
    "CoverageLedger",
    "CollectionCoverage",
    "EvidenceCoverage",
    "EvidencePage",
    "EvidenceCitation",
    "EvidenceRecord",
    "EvidenceType",
    "ExactBillNotFoundError",
    "FilesystemOfficialDocumentStore",
    "InMemoryResearchJobStore",
    "IntentEvidence",
    "InterpretedScope",
    "JobStatus",
    "LeasedResearchTask",
    "MetadataCollection",
    "MetadataCandidateResolver",
    "MetadataCollector",
    "MetadataKind",
    "MetadataPartition",
    "MetadataResolution",
    "MonthBucket",
    "OfficialDocumentKind",
    "OfficialDocumentWorker",
    "OfficialDocumentStore",
    "OfficialSource",
    "OfficialSourceKind",
    "PageProvenance",
    "ParsedOfficialDocument",
    "PartitionCoverageExpectation",
    "PartitionSearchTerm",
    "PartitionProvenance",
    "PermanentDocumentError",
    "PlannedMetadataPartition",
    "RawOfficialDocument",
    "ResearchContractPlanner",
    "ResearchCredential",
    "ResearchCredentialCodec",
    "ResearchContract",
    "ResearchIntent",
    "ResearchJob",
    "ResearchJobStore",
    "ResearchPlan",
    "ResearchPartitionPlan",
    "ResearchPartitionPlanner",
    "ResearchResultPage",
    "ResearchSnapshot",
    "ResearchTask",
    "ResearchTaskQueue",
    "ResearchTaskStage",
    "SQLiteResearchJobStore",
    "SearchTermRole",
    "StableCursor",
    "TextSegment",
    "VercelResearchTaskQueue",
    "TransientDocumentError",
    "CandidateDecision",
    "CandidateSetResolution",
    "plan_research",
    "plan_partitions",
    "resolve_metadata_candidates",
    "snapshot_payload",
]
